---
title: "Introducción a Machine Learning con R"
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment="##", fig.retina=2, fig.path = "README_figs/README-")
```

Recursos y temario del curso **Introducción a Machine Learning con R** en Kairós.

### Temario

- Introducción a R (4h)
    - IDE y Addins
    - RMarkdown notebooks
    - Librerías relevantes: tidyverse vs base
    - Reporting y visualización
- Introducción al Machine Learning (3h)
    - Selección de features y preprocesamiento de datos (normalización, computación de nulos, etc)
    - Training and testing
    - Cross validation
    - Overfitting, underfitting and the bias-variance tradeoff
- Aprendizaje supervisado (5h)
    - Modelos de regresión
    - Naive Bayes
    - Support Vector Machines
    - Árboles de decisión
- Aprendizaje no supervisado (4h)
    - PCA
    - k-means
    
### Documentación complementaria

Este curso se ha realizado gracias a decenas de información displonible para el público. Dado que no se puede enseñar todo, he recopilado la bibliografía en un [tablero de trello](https://trello.com/b/1RX5nQrA/kair%C3%B3s-clases) al que tenéis acceso.
